### ISSUE TITLE
1.18.0 Release/Post-Release Checklist

### ISSUE THREAD

**Issue by mitsuhiko** [mitsuhiko/insta#268]
Since there is a bit more to do for 1.18.0 here is a list:

* [x] bump version to 1.18.0
* [x] remove `unreleased` marker from changelog
* [x] tag 1.18.0
* [x] merge website changes https://github.com/mitsuhiko/insta-website/pull/8
* [x] release 1.18.0
* [x] remove `backtrace` feature entirely in `master` and the code hanging on it
* [x] remove `serde` from default features
* [x] ensure `yaml` related macros are only enabled with `yaml` feature
* [x] ensure `json` related macros are only enabled with `json` feature

**Comment by mitsuhiko** [comment]
Finished in 25ef917d5028e103798d8efec206e914583ab569
